#local, dev, prod 공통 설정
#profiles 선언하여 적용할 profile을 선택한다.
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: misonamoo03@gmail.com
    password: misonamoo2819
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Mybatis
mybatis:
  type-aliases-package: com.misonamoo.niaportal.domain
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  map-underscore-to-camel-case: true

# Logback 위치 지정
logging:
  config: classpath:logback-default.xml

server:
  port: 8080
---

#local 환경

spring:
  profiles: local
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://smileway.co.kr:3306/bizmiso?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: bizmiso
    password: Miso@7531

---

#dev 환경

spring:
  profiles: dev
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mariadb://st-flexer.c7wbt5xofh6c.ap-northeast-2.rds.amazonaws.com:3306/niaportal_dev?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      username: niaportal_dev
      password: 1MNL3QLY7SA

---

#prod 환경
spring:
  profiles: prod
  datasource: #TODO : prod용으로 변경 필요
    url:
    hikari:
      username:
      password:
server:
  port: 9090

---
#salt 키
key: Misonamoo
dwReqCode:
  dwReq: CD010001 #승인요청
  dwReqConfirm: CD010002 #승인
  dwReqFail: CD010003 #승인반려
  reReq: CD010004 #재승인처리
